CREATE TABLE User (
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE User ADD COLUMN user_id VARCHAR(255) NOT NULL UNIQUE;

SELECT * FROM User;
SELECT * FROM transactions;

ALTER TABLE User ADD CONSTRAINT unique_user_id UNIQUE (user_id);
ALTER TABLE User MODIFY COLUMN email VARCHAR(255) UNIQUE;
ALTER TABLE User MODIFY COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE transactions MODIFY COLUMN user_id VARCHAR(255) NOT NULL;

ALTER TABLE transactions
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES User(user_id);


SELECT user_id FROM transactions
WHERE user_id NOT IN (SELECT user_id FROM User);

DELETE FROM transactions;

